spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baohuang?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: app_user
    password: user1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/
logging:
  level:
    org.springframework.web: DEBUG